config:
  head: "&a--- ZoneMenu ---"
  head_extra: " &b(Options are clickable)"
  find: "&b>> Look for a free place."
  find_hover: "&b/zone find"
  sign: "&b>> Sign your new zone."
  sign_hover: "&b/zone sign"
  create: "&b>> Create your zone."
  create_hover: "&b/zone create"
  addmember: "&b>> Add a player to your zone."
  addmember_hover: "&b/zone addmember <Player>"
  removemember: "&b>> Remove a player from your zone."
  removemember_hover: "&b/zone removemember <Player>"
  info: "&b>> Get information about your zone."
  info_hover: "&b/zone info"
  delete: "&b>> Delete your zone."
  delete_hover: "&b/zone delete"
  cancel: "&b>> Cancel creation."
  cancel_hover: "&b/zone cancel"
  zone_find: "&bUse the stick to look for a free place by &aleft- &band &aright-click&b."
  zone_sign: "&bUse the stick to sign the &6first &bpoint by &aleft- &band the &dsecond &bpoint by &aright-click&b."
  zone_in_world: "&cYou already have a zone in this world."
  zone_not_sign: "&cSign your zone first."
  zone_area_min: 150
  zone_area_max: 15000
  zone_area_under: "&cMinimum area: &b{0}&c"
  zone_area_over: "&cMaximum area: &b{0}&c"
  zone_overlap: "&cYour zone overlaps with one or more unowned zones."
  zone_create: "&bZone created."
  no_zone: "&cYou do not have a zone in this world."
  zone_addmember: "&bThe player &a{0} &bis now member of your zone."
  zone_addmember_unknownplayer: "&cThe player &b{0} &cdoes not exist."
  zone_removemember: "&bThe player &a{0} &bis no longer member of your zone."
  zone_info_id: "&bID: &a"
  zone_info_owners: "&bOwners: &a"
  zone_info_members: "&bMembers: &a"
  zone_info_start: "&6Starting &bpoint: &aX: {0} &b/ &aZ: {1}"
  zone_info_end: "&dEnding &bpoint: &aX: {0} &b/ &aZ: {1}"
  zone_info_area: "&bArea: &a{0}"
  zone_delete: "&bZone deleted."
  zone_cancel: "&bZone creation cancelled."
  zone_already_cancel: "&cZone creation not running."
  usage_message: "&cPlease use &b{0}&c."
  permission_message: "&cYou need &b{0}&c."
  console_msg: "&cConsole? &bNo."
  event_find: "&bZone found: &a"
  event_find_multi: "&bZones found: &a"
  event_find_no: "&cNo Zones found."
  event_sign_first: "&6First &bposition marked."
  event_sign_second: "&dSecond &bposition marked."
  event_sign_area: " &bArea: &a{0}"
  zone_priority: 1
  zone_id_search: "&bSearching, please wait ..."
  zone_id: "zone_"
  zone_id_counter: 0